### ISSUE TITLE
I would like to change a word in the file "L10nMVEditor.js"

### ISSUE THREAD

**Issue by seasonside** [Creta5164/L10nMV.js#3]
This project is great, and I like it very much.
I appreciated that you made such a nice work, but an error occurred in L10nMVEditor.js.
The word "ISO639_1" in L10nMVEditor.js is not the same as the word "Iso639_1" in L10nMV.js.
I changed the "ISO639_1" to "Iso639_1" and then it works.

**Comment by Creta5164** [comment]
Thanks to report specifically! I'll fix this soon.

**Comment by Creta5164** [comment]
Fixed in 1.4.5.
