### ISSUE TITLE
특정 스크립트와 화이트리스트 충돌 오류 ? 

### ISSUE THREAD

**Issue by mitenbets** [Creta5164/L10nMV.js#5]
![image](https://user-images.githubusercontent.com/97384041/152627886-cdad3f5d-fccb-4275-87d9-a6262d30945e.png)

L10nMVEditor.CreateTemplate() 을 실행하니 이런 에러가 뜹니다.

좀 더 해보니 YEP_OptionsCore가 화이트리스트에 있어 일어났습니다.

이것을 제외하고 다른 플러그인을 화이트리스트에 추가하고 실행하면 문제 없이 진행됩니다.

**Comment by Creta5164** [comment]
예외 처리가 되지 않은 부분이 있는 것 같습니다.  
제가 프로젝트 파일을 통해 문제를 확인해봐야 알 수 있을 것 같네요.

**Comment by Creta5164** [comment]
This issue was happed not valid array and object keys because defined from other plugins such as defines `Array.prototype.merge` etc.  
This problem has solved by using `.hasOwnProperty(...)`.

**Comment by Creta5164** [comment]
Fixed in `1.4.7`.
